<h1 id="tocheading">NumPy基础</h1>
<div id="toc"></div>

# 2 NumPy基础

## 2.1 数组对象

NumPy中ndarray是一个多维数组对象，由两部分组成

+ 实际数据
+ 描述这些数据的元数据

大多少数组操作，仅修改元数据，不改变底层实际数据

`arange` 可以创建一维数组，`ndarray`支持更高维度。

NumPy数组一般是同质的，即数组中所以元素类型必须一致（有例外）。



In [102]:
# 一维数组
import numpy as np
a = np.arange(5)
a.dtype


# 结果
# 我是： dtype('int32')
# 书中是： dtype('int64')
# 纯python： dtype('int64')
# anaconda （py2，py3）：dtype('int32')

dtype('int64')

In [103]:
a

array([0, 1, 2, 3, 4])

In [104]:
a.shape

(5,)

In [105]:
# 多维数组
# import numpy as np
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [106]:
m.shape

(2, 2)

### 习题
创建3X3数组

In [107]:
trip_array = np.array([np.arange(3),np.arange(3),np.arange(3)])

In [108]:
trip_array.shape

(3, 3)

## 选取数组元素


In [109]:
# array 仅接受 一个参数
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [110]:
a[0,0]

1

In [111]:
a[0,1]

2

In [112]:
a[1,0]

3

In [113]:
a[1,1]

4

<table>
<tr><tb>[0,0]</tb><tb>[0,1]</tb></tr>
<tr><tb>[1,0]</tb><tb>[1,1]</tb></tr>
</table>

<h1 id="tocheading">NumPy数据类型</h1>
<div id="toc"></div>

## NumPy数据类型

Python内置 整型、浮点型、复数类型

Numpy

类型 | 描述
----|----
bool| 一位
inti| 平台决定精度（一般int32或int64）
int8| -128~127
int16| -23768~32767
int32| $-2^{31}到2^{31} -1$
int64| $-2^{63}到2^{63} -1$
unit8| 无符号，0~255
...|

数据类型也有对应`字符编码`，不推荐使用 （如：整数 i)

In [114]:
# 书中 dtype 具体类型没加 引号
temp = np.arange(7, dtype='uint16')
temp

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [115]:
temp.dtype.itemsize

2

In [116]:
# 完整NumPy数据类型列表

np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'float128', 'Float128', 'f16', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'complex256', 'Complex128', 'c32', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int32', 'uint32', 'Int32', 'UInt32', 'i4', 'u4', 'int16', 'uint16', 'Int16', 'UInt16', 'i2', 'u2', 'int8', 'uint8', 'Int8', 'UInt8', 'i1', 'u1', 'complex_',

## dtype 类属性

In [117]:
t = np.dtype('float64')
t.char

'd'

In [118]:
# type 属性对应数组 元素 的数据类型
t.type

numpy.float64

In [119]:
# big-endian 大端序，将最高位字节存储在最低内存地址处 用 > 表示
# little-endian 小端序， 将最低位字节存储在最低位内存地址处， 用 < 表示
t.str

'<f8'

## 创建自定义数据类型

In [120]:
t = np.dtype([('name', 'str_', 40), ('numitems', 'int32'), ('price', 'float32')])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [121]:
# 查看某一字段数据类型
t['name']

dtype('<U40')

array 创建数组时，如果没有指定类型，默认为__浮点类型__。
下面用自定义类型创建数组

In [122]:
items = np.array([('Meaning of Life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype = t )
items[1]

('Butter', 13,  2.72000003)

## 一维数组索引切片

In [123]:
a =np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [124]:
a[:7:2]

array([0, 2, 4, 6])

In [125]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

## 多维数组索引切片

In [126]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [127]:
b.shape

(2, 3, 4)

In [128]:
b[:,0,0]

array([ 0, 12])

In [129]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
b[0,1]

array([4, 5, 6, 7])

In [132]:
b[0,1,:]

array([4, 5, 6, 7])

In [133]:
b[0,1,::2]

array([4, 6])

In [134]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [135]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [136]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [137]:
b[0,:,-1]

array([ 3,  7, 11])

In [138]:
b[0,::-1,-1]

array([11,  7,  3])

In [139]:
b[0,::2,-1]

array([ 3, 11])

In [140]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## 改变数组维度

+ ravel 数组展平，仅返回一个视图
+ flatten 数组展平，会请求内存保存结果
+ 直接用元组设置维度
+ transpose 转置
+ resize，和reshape功能一样，但会直接修改数组

In [141]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [142]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [143]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [144]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [145]:
b.shape=(6,4)

In [146]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [147]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [148]:
b.resize((2,12))

In [149]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## 数组的组合

In [150]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
b = 2*a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### 水平组合

In [152]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [153]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

### 垂直组合

In [154]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [155]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### 深度组合

In [156]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [157]:
c = np.dstack((a,b))
np.dstack((c,b))

array([[[ 0,  0,  0],
        [ 1,  2,  2],
        [ 2,  4,  4]],

       [[ 3,  6,  6],
        [ 4,  8,  8],
        [ 5, 10, 10]],

       [[ 6, 12, 12],
        [ 7, 14, 14],
        [ 8, 16, 16]]])

### 列组合

column_stack 函数对一维数组按列方向组合

In [158]:
oned = np.arange(2)
oned

array([0, 1])

In [159]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [160]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [161]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [162]:
np.column_stack((a, b)) == np.hstack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### 行组合


In [163]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [164]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [165]:
np.row_stack((a, b)) == np.vstack((a,b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## 数组的分割

In [166]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 水平分割 ? 翻译错？

In [167]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [168]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

### 垂直分割?

In [169]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [170]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

### 深度分割

In [171]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

## 数组的属性

In [173]:
b=np.arange(24).reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [174]:
b.ndim

2

In [175]:
b.size

24

In [176]:
b.itemsize

8

In [177]:
b.nbytes

192

In [178]:
b.resize(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [179]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [180]:
b.shape=(24,)

In [181]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [182]:
b.ndim

1

In [183]:
b.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [184]:
b=np.array([1.j + 1, 2.j + 3])
b

array([ 1.+1.j,  3.+2.j])

In [185]:
b.real

array([ 1.,  3.])

In [186]:
b.imag

array([ 1.,  2.])

In [187]:
b.dtype

dtype('complex128')

In [188]:
b.dtype.str

'<c16'

+ flat 属性返回一个numpy.flatiter对象，这是获得flatiter对象的唯一方式
+ flat 属性是一个可赋值属性。对flat属性赋值，将导致整个数组元素被覆盖

In [189]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [190]:
f = b.flat
f

In [191]:
b.flat[2]

2

In [192]:
b.flat[[1,3]]

array([1, 3])

In [193]:
b.flat =7
b

array([[7, 7],
       [7, 7]])

In [194]:
b.flat[[1,3]]=1
b

array([[7, 1],
       [7, 1]])

## 数组的转换

In [195]:
b

array([[7, 1],
       [7, 1]])

In [196]:
b.tolist()

[[7, 1], [7, 1]]

In [197]:
b.astype(int)

array([[7, 1],
       [7, 1]])

In [198]:
b=np.array([1.j + 1, 2.j + 3])
b.tolist()

[(1+1j), (3+2j)]

In [199]:
b.astype(int)

/home/vicky/anaconda3/envs/py36R/lib/python3.6/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 3])

In [200]:
b.astype('complex')

array([ 1.+1.j,  3.+2.j])

In [201]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>